export interface SeedProduct {
  code: string;
  name: string;
  description: string;
  properties: string;
  price: number; // in COP
  category: string;
  image_url: string;
  initial_stock: number;
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    code: "10",
    name: "Yupi Rizadas Mayonesa",
    description: "Ridged potato chips, mayonnaise flavor",
    properties: "105 g",
    price: 2500,
    category: "Snacks & Chips",
    image_url: "https://product-images.farmatodo.com/lQgd0H6OGfxdOGa6cOIiHBGwjnx9eNfd9M9aVwRStCMyFk-rhRg6f2cptz1H3qE7_8gqwjg8eZdh_GphvaMQVZpVlAvH9pgsHGJtpRUegQ_YjbJR",
    initial_stock: 45,
  },
  {
    code: "11",
    name: "Yupi Rizadas Limón",
    description: "Ridged potato chips, lemon flavor",
    properties: "105 g",
    price: 2500,
    category: "Snacks & Chips",
    image_url: "https://product-images.farmatodo.com/_d1SKedV8ac9EFrhWhKFackUlHxk12mFPVdU6o4Wcwrcs_eAkha0obUBt2UMMCo2ZcQ4i1Xoqa8GZpKuFVRKuUuhmUVUxr7p7fcrLuXhitbn7ZeK",
    initial_stock: 35,
  },
  {
    code: "14",
    name: "Yupi Tocinetas / El Golpe",
    description: "Potato, plantain and wheat snack, bacon flavor",
    properties: "45 g",
    price: 2000,
    category: "Snacks & Chips",
    image_url: "https://product-images.farmatodo.com/THsTuYgsxrYaIBvFi4khd1qRbWAHRNc-07ZVr16N6XdYVjDpE7rppFIpZ-paNur1d6jkuTaI2_j-MHvI7XHhGoEYZ62Q-ldD--A1aJwEpwVHMEVY",
    initial_stock: 50,
  },
  {
    code: "20",
    name: "Las Caseritas Rosquitas",
    description: "Baked cassava and cheese ring snacks",
    properties: "~16 g/unit",
    price: 2200,
    category: "Bakery & Snacks",
    image_url: "https://mercaldas.vtexassets.com/arquivos/ids/1345919-800-auto?v=638802600250400000&width=800&height=auto&aspect=true",
    initial_stock: 40,
  },
  {
    code: "23",
    name: "Bimbo Chocoso",
    description: "Baked vanilla sponge cake with chocolate coating",
    properties: "65 g",
    price: 2300,
    category: "Bakery & Cakes",
    image_url: "https://d108z12oqgp5bp.cloudfront.net/s3fs-public/product_bread_bimbo/BCO-B6483-06-I25_ENV_PONQ_CHOCOSO_1P_65G_BIM%20400x400.png",
    initial_stock: 30,
  },
  {
    code: "30",
    name: "Festival Limón",
    description: "Cookie filled with lemon-flavored cream",
    properties: "403 g",
    price: 1800,
    category: "Cookies & Biscuits",
    image_url: "https://tutiendalatina.es/662-large_default/galletas-festival-limon.jpg",
    initial_stock: 60,
  },
  {
    code: "31",
    name: "Festival Chocolate",
    description: "Chocolate cookie filled with cream",
    properties: "403 g",
    price: 1800,
    category: "Cookies & Biscuits",
    image_url: "https://jotajotafoods.com/wp-content/uploads/2024/03/GAL00056.jpg",
    initial_stock: 55,
  },
  {
    code: "32",
    name: "Festival Vainilla",
    description: "Cookie filled with vanilla-flavored cream",
    properties: "403 g",
    price: 1800,
    category: "Cookies & Biscuits",
    image_url: "https://jotajotafoods.com/wp-content/uploads/2024/03/GAL00057.jpg",
    initial_stock: 50,
  },
  {
    code: "34",
    name: "Tosh Crackers Fusión de Cereales",
    description: "Multigrain whole-wheat crackers",
    properties: "25.5–229 g",
    price: 1750,
    category: "Cookies & Biscuits",
    image_url: "https://megatiendas.vtexassets.com/arquivos/ids/170872-800-auto?v=638597574219700000&width=800&height=auto&aspect=true",
    initial_stock: 40,
  },
  {
    code: "36",
    name: "Jumbo Chocolate con Maní",
    description: "Milk chocolate bar with peanuts",
    properties: "40 g",
    price: 2000,
    category: "Confectionery & Chocolates",
    image_url: "https://mecato.shop/cdn/shop/products/chocolatina-jumbo-2.jpg?v=1642800058",
    initial_stock: 75,
  },
  {
    code: "38",
    name: "Gol Mega",
    description: "Chocolate-covered wafer/cookie",
    properties: "53 g",
    price: 2200,
    category: "Confectionery & Chocolates",
    image_url: "https://product-images.farmatodo.com/Cuu6k5eRY6gudjw3sa9-pQg_03mvW3EUIONeX4xRLUI5Y8z2XMq9PxECz8iA5eWD-tJ8W3UdnGYugTz7F7ifRHpz42u80w_UldjD9fn52Dpm6XN5",
    initial_stock: 45,
  },
  {
    code: "40",
    name: "Alpin Chocolate",
    description: "UHT chocolate milk drink",
    properties: "200 ml",
    price: 2800,
    category: "Dairy & Beverages",
    image_url: "https://alpina.com/media/catalog/product/cache/27defdc4d2877e4b183fddab68dad6a4/7/7/7702001044306_1.png",
    initial_stock: 35,
  },
  {
    code: "42",
    name: "Alpina Avena Original",
    description: "UHT milk and oat drink",
    properties: "280 g",
    price: 2700,
    category: "Dairy & Beverages",
    image_url: "https://alpina.com/media/catalog/product/cache/27defdc4d2877e4b183fddab68dad6a4/7/7/7702001163205_2.png",
    initial_stock: 30,
  },
  {
    code: "43",
    name: "Alquería Avena Pro Auténtica",
    description: "Oat drink with magnesium, provides energy",
    properties: "220 ml",
    price: 3200,
    category: "Dairy & Beverages",
    image_url: "https://alqueriauploads.s3.us-east-1.amazonaws.com/prod/Avena_Pro_Autentica_4755981db1.png",
    initial_stock: 25,
  },
  {
    code: "47",
    name: "Ducales",
    description: "Salted cracker-style cookie",
    properties: "403 g",
    price: 1700,
    category: "Cookies & Biscuits",
    image_url: "https://tutiendalatina.es/778-home_default/galletas-ducales.jpg",
    initial_stock: 65,
  },
  {
    code: "51",
    name: "Coca-Cola Zero",
    description: "Sugar-free cola soda",
    properties: "600 ml",
    price: 3200,
    category: "Beverages & Sodas",
    image_url: "https://lh3.googleusercontent.com/RVuui8_xzR14_v90DbgD0L9MrPCRZTJAr2ywQJ0sBFbRMN8FjBjlu-w3Idj4qcPmS4PbNHWjzq6JHlivTPh3M_zpt3TTMEvckbAMNCA3nxTetK_D",
    initial_stock: 50,
  },
  {
    code: "52",
    name: "Coca-Cola Original",
    description: "Classic cola soda",
    properties: "400 ml",
    price: 3200,
    category: "Beverages & Sodas",
    image_url: "https://product-images.farmatodo.com/mHS8v_sZ8giWdUo4JygSD9HN6OG1f1BaiMoue8fbkJLcJEurVWzsKVtWf9Q-vbMxeQhaQEA3yANB8P4MOt16xsSkdErFn-xCAdsS2bE6YQ_lO6o",
    initial_stock: 60,
  },
  {
    code: "55",
    name: "Brisa Lima-Limón",
    description: "Carbonated lime-lemon flavored water",
    properties: "400/600 ml",
    price: 2800,
    category: "Beverages & Waters",
    image_url: "https://www.coca-cola.com/content/dam/onexp/co/es/brands/brisa/nuevos/brisa-lima-limon.png",
    initial_stock: 40,
  },
  {
    code: "56",
    name: "Brisa Manzana",
    description: "Carbonated apple-flavored water",
    properties: "400/600 ml",
    price: 2800,
    category: "Beverages & Waters",
    image_url: "https://www.coca-cola.com/content/dam/onexp/co/es/brands/brisa/nuevos/brisa-manzana.png",
    initial_stock: 40,
  },
  {
    code: "57",
    name: "Postobón Manzana",
    description: "Apple-flavored soda",
    properties: "400 ml",
    price: 2950,
    category: "Beverages & Sodas",
    image_url: "https://product-images.farmatodo.com/cW-uYA2g99vPBUA1bEB8i7zNu_G4GaXPUa21uoMH9E6SdTQASaWjJt0721xuorTbQEtwRdyosnsOhleI0x-fxsAysdIJgImUwV1MZNW2zHpHk0w",
    initial_stock: 45,
  },
  {
    code: "66",
    name: "Hit Mora",
    description: "Blackberry-flavored refreshment/nectar",
    properties: "500 ml",
    price: 3250,
    category: "Beverages & Juices",
    image_url: "https://product-images.farmatodo.com/5VoTDFZkjnzgZj6jDyBOV_J8W9Nxfg8kqoMaz-_7GG_zU1y911izfgsLR7qVXw0RnNJaq3eesw5zm8Fkzbes6uYO9IBMIFm3bk3cTdiWayVMaI8E",
    initial_stock: 35,
  },
  {
    code: "69",
    name: "Mr. Tea Limón Menta",
    description: "Iced tea, lemon and mint flavor",
    properties: "500 ml",
    price: 2800,
    category: "Beverages & Teas",
    image_url: "https://product-images.farmatodo.com/FDw1dpPvnvJri4YPtHo3adUDgaSnl-FrxcpLs_Aboy1s3an2w3y9TOrUziHFxLbVaYXFagd5yhTJX9w6-F-95QN-8wlekLGmH9dQWYs0Tajpk7zW",
    initial_stock: 30,
  },
];
